import { useState } from "react";
import Head from "next/head";
import { JetBrains_Mono } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";
import Register from "@/components/Auth/Register";
import Login from "@/components/Auth/Login";

const jetbrains = JetBrains_Mono({ subsets: ["latin"] });

export default function Home() {
  const [signInType, setSignInType] = useState(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={jetbrains.className}>
        <Navbar setSignInType={setSignInType} />
        {signInType === "register" ? <Register /> : <Login />}
      </main>
    </>
  );
}
