import Head from "next/head";
import { Inter } from "next/font/google";
import Modal from "./components/Modal/Modal";
import Navbar from "./components/Navbar/Navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [modalIsOpen, setModalIsOpen] = useState(false);

  const showModal = () => {
    setModalIsOpen(!modalIsOpen);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar showModal={showModal} />
        {modalIsOpen && <Modal showModal={showModal} />}
      </main>
    </>
  );
}
